---
:text:
  :lenny: '( ͡° ͜ʖ ͡°)'
  :shrug: '¯\_(ツ)_/¯'
  :support: |-
    ⚙ **Need help?**
    You can join the support server here:
    **https://discord.gg/43SaDy6**
  :facedesk: https://giphy.com/gifs/XLOsdacfjL5cI
  :smea: https://giphy.com/gifs/Sb2NkTl1oV6eI
:image:
  :soon: assets/dab.jpg
