a: <a:r_letter_a:393623734344351744>
b: <a:r_letter_b:393623734034104322>
c: <a:r_letter_c:393623734176448512>
d: <a:r_letter_d:393623734168190996>
e: <a:r_letter_e:393623733937373185>
f: <a:r_letter_f:393623734268985346>
g: <a:r_letter_g:393623734055075841>
h: <a:r_letter_h:393623734549741568>
i: <a:r_letter_i:393623734616981514>
j: <a:r_letter_j:393623734323249174>
k: <a:r_letter_k:393623734461792257>
l: <a:r_letter_l:393623734621306881>
m: <a:r_letter_m:393623734813982720>
n: <a:r_letter_n:393623734696542209>
o: <a:r_letter_o:393623735011246080>
p: <a:r_letter_p:393623734931554305>
q: <a:r_letter_q:393623735137206272>
r: <a:r_letter_r:393623735065903114>
s: <a:r_letter_s:393623735132749824>
t: <a:r_letter_t:393623735002988545>
u: <a:r_letter_u:393623735229218816>
v: <a:r_letter_v:393623735216898049>
w: <a:r_letter_w:393623735388602368>
x: <a:r_letter_x:393623735028154369>
y: <a:r_letter_y:393623735233675265>
z: <a:r_letter_z:393623735376150550>
"1": <a:r_letter_1:393623734344220673>
"2": <a:r_letter_2:393623734180642837>
"3": <a:r_letter_3:393623734109601812>
"4": <a:r_letter_4:393623734147088384>
"5": <a:r_letter_5:393623733731983362>
"6": <a:r_letter_6:393623733962539019>
"7": <a:r_letter_7:393623734075785216>
"8": <a:r_letter_8:393623734155739136>
"9": <a:r_letter_9:393623734101213194>
"!": <a:r_letter_exclaim:393623734377906176>
"$": <a:r_letter_dollar:393623734344351774>
"&": <a:r_letter_and:393623733761212427>
"@": <a:r_letter_at:393623734122053632>
" ": " "
".": "."
